Add terraform support for security features
bingosummer/aks-samples pull request #18
Opened 2023-08-04 07:40 UTC by jiashun0011

2023-08-04 07:46 UTC, bingosummer requested changes

2023-08-04 07:46 UTC, bingosummer commented on .github/workflows/pull-request.yml
> +        echo ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
remove this line

2023-08-04 08:10 UTC, jiashun0011 commented on .github/workflows/pull-request.yml
> +        echo ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
Updated.

2023-08-07 05:34 UTC, bingosummer approved these changes

2023-08-07 05:34 UTC, merged